### ISSUE TITLE
关于模型的问题

### ISSUE THREAD

**Issue by edfall** [yilirin/BDCI_Car_2018#3]
- 看了bert的模型结构，发现模型的pipeline是：预测主题 => 预测主题极性（3分类）；但是主题预测错误在情感极性中会不断积累。

-  如果直接使用情感极性模型的结构，直接预测模型在所有主题上的情感极性（4分类， 3极性 + 1主题是否存在），这样的做法效果会更好么？

- 因为作者的模型结构中，Bert情感极性训练集直接使用的原始数据，而不是主题预测的结果下的情感极性数据，因此相关数据的precision，recall，f1好像并没有太大的意义。是否方便公布一下使用bert单模型在kflod valid上的实际效果。

**Comment by yilifzf** [comment]
- 四分类的确是一种做法，包括今年的EMNLP在内也有一些文献在探讨不使用pipeline来做这个任务。但是我没有实验过，所以不清楚哪一种更好。我选择pipeline主要有三个原因。第一可以更方便的看哪一步是性能的瓶颈分开处理，避免混在一起。第二，我认为“不存在”和“正面，负面，中性”不是一个语义空间里的东西，所以我觉得把这样的分类有点奇怪。第三，如果做四分类，那么类别的不平衡会更加严重。
- 5折的结果为：[0.7597, 0.7468, 0.7409, 0.7301, 0.7341]。训练时的metric只是为了对比模型。
