### ISSUE TITLE
关于Elmo的hdf5

### ISSUE THREAD

**Issue by Cooper111** [yilirin/BDCI_Car_2018#6]
萌新请教一下如何制作elmo的句向量……？源码里有对应的预处理吗？

**Comment by yilifzf** [comment]
我用的是HIT-SCIR的脚本：https://github.com/HIT-SCIR/ELMoForManyLangs ，具体参考他们的说明，不过该项目相比我当时使用的版本已经更新了，所以他们现在的代码可能和这个项目有不兼容的问题。而且这里还是有一些坑的，需要注意tokenize，输入格式，特殊字符的处理等等，最好阅读一下他们的脚本，保证输入的句子能找到对应的向量。
