### ISSUE TITLE
如何在分类任务中使用预训练ELMo模型

### ISSUE THREAD

**Issue by OswaldoBornemann** [yilirin/BDCI_Car_2018#7]
您好，我现在已经下载了中文简体的ELMo模型，并且执行了github页面的一些基本操作。
但是我不太了解如何用pytorch把ELMo预训练模型用在后续分类任务中，我看了一些issue说可以参考word2vec的应用方法，但是word2vec是静态词向量，而且我还看到部分issue说目前HIT的ELMo无法和allennlp结合使用。

因此您方便提供一些Pytorch使用例子吗？感激不尽。

**Comment by yilifzf** [comment]
使用elmo主要有两种方式：
1. 类似于word2vec将句子中的每个词映射到一个dense vector，这种方法在后续训练过程词向量的表示是不更新的。但是它还是和word2vec的静态不同，因为它依然保证了同一个词在不同的上下文下有不同的表示。具体实现上都是事先将训练集和测试集的所有句子先预先计算出ELMo表示，然后存为dict，使用时再取出来一个和句子等长的vector序列，然后转为tensor就可以直接用pytorch处理了。
2. 将ELMo作为一个网络模块嵌入到你的模型之中。这种做法可以选择是否让ELMo模块fine tune从而让词向量得到训练更新。HIT实现的ELMo和AllenNLP最原始的ELMo是有区别的所以可能无法兼容，而且HIT的ELMo在这个任务上效果一般。你也可以尝试用allennlp的代码自己训一个中文ELMo，这样可以很方便的和allenlp的api对接。

具体可以看本项目里的主要运行代码以及allennlp的指导：
https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md

**Comment by OswaldoBornemann** [comment]
感谢大佬。。因为我看了您的代码。。说实话可能过于高深没看太懂。。您是否是用第二种方法的。。

**Comment by yilifzf** [comment]
我用的是第一种。
https://github.com/yilirin/BDCI_Car_2018/blob/cc1b0193213ed77f3403ee663ec210056f883888/attribute_level/attribute.py#L107

**Comment by OswaldoBornemann** [comment]
大佬早上好～非常感谢！！

**Comment by OswaldoBornemann** [comment]
大佬 您好 想问下batch之后的train data应该是已经padding了，但是ELMo应该不会返回padding的词向量。所以在concat两个词向量的时候 可能会出现长度不一样的情况，这时候应该怎么解决？

譬如说

```
batch = next(iter(train_iter))
print(batch.text)

tensor([[   3, 1066],
        [ 234,  889],
        [ 724, 1015],
        [   6,    1]])
```

`1`就是那个padding。

```
embedding = nn.Embedding(len(TEXT.vocab), 3)
embedding = nn.Embedding(len(TEXT.vocab), 3)
print(embeds.shape)
torch.Size([4, 2, 3])
```
但是ELMo在返回第二个向量的时候，应该只有3个词的词向量。

**Comment by yilifzf** [comment]
怎么padding需要看你具体的模型，简单的就直接补零就行了，如果你是RNN需要记录一下序列长度。我不是很清楚allennlp或者torchtext的api能不能直接做ELMo的padding，如果让我来做的话，我可能不会借用这些工具来处理ELMo的padding问题，只需要手动padding ELMo，然后在建batch的时候保证sentence_id对应就行了。不过也是因为比较麻烦以及比赛时间有限，所以这个代码里面我都没有做padding并且把batch设为1，当然不推荐这么做。

**Comment by OswaldoBornemann** [comment]
您好 已经解决了 我用numpy直接将padding出现的地方都用0代替。但我发现实际结果并没有提升很多。。好像加和没加并没有太影响结果？您是否有类似的发现？

**Comment by yilifzf** [comment]
在这个数据集上，我用HIT-SCIR的ELMo的单模型性能不如使用word embedding的单模型，但是在其他地方英文的ELMo效果还是很明显的，可能要看具体任务吧。

**Comment by OswaldoBornemann** [comment]
谢谢大佬～目前正在研读大佬您BERT的代码～打算试试BERT
