### ISSUE TITLE
直接拿 BERT 做情感极性预测的准确率

### ISSUE THREAD

**Issue by TobiasLee** [yilirin/BDCI_Car_2018#8]
Hello，我用 BERT 在 train data 上直接做情感的三分类，在 valid set （500 条） 上的准确率大约在 75% 左右，此外也拿 SVM 和 Naive Bayes 做了一下 baseline，准确率在 73% 左右，想请教一下这样的效果是否合理?

**Comment by yilifzf** [comment]
请问跑的也是这个数据集和相同的任务吗？以及SVM和NB的输入特征是怎么构建的，类似于TF-IDF？有考虑输入的aspect吗？我个人感觉差距应该不只两个点。不过也有可能是数据集的原因，500条做验证集也许有一点小，或者多次采样做交叉验证会更准一点。

**Comment by TobiasLee** [comment]
对，同样的数据集，用的是 TF-IDF 做特征，没有考虑 Aspect；不过我看之前一个 Issue 里的 5-fold 也是在 0.75 左右? 那个是 accuracy 吗？

**Comment by yilifzf** [comment]
是accuracy, 但是你的BERT有考虑aspect吗？其实2个点已经是蛮大的差距了，虽然比预想的可能要低一些。

**Comment by TobiasLee** [comment]
没有喔，因为我想先看看情感三分类的准确度。还有一点蛮奇怪的是我看了下 SVM 和 NB 以及 BERT 的 precision 和 recall，在这两个指标上 BERT 基本上在 90+，SVM 在 70 左右 NB 50 不到。accuracy 一般不是和 precision 和 recall 正相关吗，有点迷... Anyway，感谢回复， 我再看看~

**Comment by yilifzf** [comment]
如果不考虑aspect直接做三分类是不合适的，所以BERT的性能因此被限制了。在评价的时候如果不考虑aspect会有很多句子相同但是label不同的情况，不知道会不会影响具体metric的计算。

**Comment by TobiasLee** [comment]
是的，我检查了一些例子，有些一句话里面两个 aspect 一个好一个坏，人都不怎么好判断。谢谢！
