### ISSUE TITLE
../embedding/cc.zh.300.bin not found

### ISSUE THREAD

**Issue by WangKK1996** [yilirin/BDCI_Car_2018#9]
尊敬的作者您好！

我最近在读您的代码，然后尝试代入自己语料跑一跑，但是在w2v时没有找到这个文件，想请问作者是用的什么做的w2v，谢谢啦！

**Comment by WangKK1996** [comment]
我知道问题出在哪里了，已解决。

**Comment by desktoop** [comment]
我也遇见了这个问题，请问你是怎么解决的呀？
